import { bootstrapApplication } from '@angular/platform-browser';
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  imports: [FormsModule],
  template: `

    {{title}}
    <hr>
    @for (variable of variableList(); track [$index]; let i = $index) {   <!-- by this loop the UI look will generated by the variableList array -->
      <table>
        <tr>
          @if (typeof variable === "object"){
            <td>
              {{variable.variableName}} :
            </td>
            <td>
              <input
                (keyup)="keyup(variable)"
                [(ngModel)]='variable.inputValue'>
            </td>
          }
        </tr>

        @if ( variable == 'br') {  <br> }
        @if (typeof variable === "string" && (variable) != 'br') { <p> {{ variable }} </p> }
      </table>
    }
  `,

  styles: ['html { line-height: 1.15;} input{border: 0.1em solid lightgreen;}'],
})
export class App {
  // for the formular x * 2 = y
  protected title = 'signalasobjects for 2x=y';

  x: VariableBuilder = new VariableBuilder('X', 'mm', 0);
  y: VariableBuilder = new VariableBuilder('Y', 'mm', 0);
  variableList = signal<(string | VariableBuilder)[]>([]); // List to scaffolding the html structure
  msg = 'MSG';

  constructor() {
    this.variableList.update((items) => [
      ...items,
      this.x, // here is the first item of the HTML table element
      '*2 = ', // here is the next item of the HTML table element
      this.y,
      'br',
      '_______________________________',
      'That is OK?',
    ]);
  }

  keyup(obj: IVariableBuilder): void {
    // here some validation may done

    const methodCall = ('keyup_' +
      obj.variableName) as keyof typeof this.keyupFunctionObj; // here the prop is needed for deligation matter

    try {
      // here the related function for the variable is invoked

      this.keyupFunctionObj[methodCall](obj); // related sub-function to the object input will be invoked
    } catch (e) {
      console.log(e + 'Subfunction have to be inplemented');
    }
  }

  // sub-functions refer to the changed input variable value  keyup_...(obj)
  keyupFunctionObj = {
    keyup_X: (obj: IVariableBuilder) => {
      this.y.inputValue = Number(this.x.inputValue) * 2; // not pure function
      this.ChangeUpdater(obj);
    },
    keyup_Y: (obj: IVariableBuilder) => {
      this.x.inputValue = Number(this.y.inputValue) / 2; // not pure function
      this.ChangeUpdater(obj);
    },
  };

  keyup_X(obj: IVariableBuilder): void {
    this.y.inputValue = Number(this.x.inputValue) * 2; // not pure function
    this.ChangeUpdater(obj);
  }

  keyup_Y(obj: IVariableBuilder): void {
    this.x.inputValue = Number(this.y.inputValue) / 2; // not pure function
    this.ChangeUpdater(obj);
  }
  // Helper or service function normally into differ folder
  ChangeUpdater(obj: IVariableBuilder): void {
    this.variableList.update((items) => [...items]); // to trigger changedetection?
  }
}

interface IVariableBuilder {
  variableName: string; // to get information, which variable was changed by <input>
  inputValue: number | string | (number | string)[]; // the value of the <input> field
  varLabel: string;
  varSymbol: string;
  nominalValue: number; // value related to baseUnit
  baseUnit: string; // possible SI unit
  selectedUnit: string; // derivative from baseUnit : mm -> cm -> .. -> km
  scaleSelect: number;
  isComputed: boolean; // this variable will be only computed
  isSelectBox: boolean;
}

export class VariableBuilder implements IVariableBuilder {
  variableName = ''; // to get information, which variable was changed by <input>
  public varLabel: string = '';
  public varSymbol: string = '';

  inputValue: number | string | (number | string)[] = '';

  nominalValue = 0; // value related to baseUnit
  baseUnit = ''; // possible SI unit
  selectedUnit = ''; // deviated from baseUnit e,g, "mm" - "cm" ... "km"
  scaleSelect: number = 1; // BaseUnit scale will e everytime 1
  isSelectBox: boolean = false;
  isComputed: boolean = false;

  constructor(
    variableName: string,
    baseUnit: string,
    inputValue: number | string | (number | string)[] = '',
    varLabel?: string,
    varSymbol?: string,
    isComputed?: boolean,
    isSelectBox?: boolean
  ) {
    this.variableName = variableName;
    this.inputValue = inputValue;
    this.baseUnit = baseUnit;
    this.selectedUnit = baseUnit;
    this.isSelectBox = isSelectBox || false;
    this.isComputed = isComputed ? isComputed : false;

    typeof inputValue === 'number' && inputValue
      ? (this.inputValue = inputValue)
      : 0;
    typeof inputValue === 'string' && inputValue
      ? (this.inputValue = inputValue)
      : '';

    try {
      // for a selection boy as input value
      if (Array.isArray(inputValue) && inputValue.length > 1) {
        // could be also checked for isSelectBox == true;
        const firstElement = inputValue[0];
        if (typeof firstElement === 'string') {
          this.nominalValue = parseFloat(firstElement);
          this.inputValue = firstElement;
        } else {
          {
            this.nominalValue = firstElement;
            this.inputValue = firstElement.toString();
          }
        }
        this.isSelectBox = true;
      }
    } catch (e) {}

    varLabel ? (this.varLabel = varLabel) : (this.varLabel = variableName);
    varSymbol ? (this.varSymbol = varSymbol) : (this.varSymbol = variableName);
  }
}

bootstrapApplication(App);
