export const labelColor = {
  downloadNok: 'maroon',
  evtUpdNok: 'red',
  evtUpdStr: 'navy',
  updDwldNok: 'maroon',
  updDwldOk: 'olive',
  updDwldStr: 'blue',
  evtUpdOk: 'green',
  updAbrt: 'purple',
  condCheckFailed: 'orange',
  condCheckOk: 'lime',
  avalChkIstl: 'limegreen',
  evtWCNotConn: 'orange',
  invUnk: 'orange',
  comMissing: 'orange',
  evtComLoginFail: 'orange',
  updTransmissionStart: 'blue',
  updTransmissionNok: 'maroon',
  updTransmissionOk: 'green',
  pkgRevDevNok: 'orange',
  evtUpdFileFmt: 'orange',
};
